project_id = "wsuljngcdfagrkbtxltb"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.create-daily-room]
verify_jwt = false

[functions.end-call]
verify_jwt = false

[functions.calculate-family-lines]
verify_jwt = false

[functions.send-phone-otp]
verify_jwt = false

[functions.verify-phone-otp]
verify_jwt = false

[functions.r2-upload]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.ai-chat-groq]
verify_jwt = false

[functions.ai-image-gen]
verify_jwt = false

[functions.fetch-shorts]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = false
[functions.send-push-notification]
enabled = true
verify_jwt = false
import_map = "./functions/send-push-notification/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-push-notification/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-push-notification/*.html" ]
